// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage-variants/AlexandriaBlend.tsx": () => import("../components/mockups/homepage-variants/AlexandriaBlend.tsx"),
  "./components/mockups/homepage-variants/DiagnosticWizard.tsx": () => import("../components/mockups/homepage-variants/DiagnosticWizard.tsx"),
  "./components/mockups/homepage-variants/PackageFirst.tsx": () => import("../components/mockups/homepage-variants/PackageFirst.tsx"),
  "./components/mockups/homepage-variants/PremiumGarage.tsx": () => import("../components/mockups/homepage-variants/PremiumGarage.tsx"),
  "./components/mockups/homepage-variants/TrustLed.tsx": () => import("../components/mockups/homepage-variants/TrustLed.tsx")
};
